### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by 4N1S** [cokeeffekt/pokebot-ui#1]
Install ok !
connection avec utilisateur crash

pokebot-ui/node_modules/pokemon-go-node-api/node_modules/protobufjs/node_modules/bytebuffer/dist/bytebuffer-node.js:346
            throw TypeError("Illegal buffer");
            ^

TypeError: Illegal buffer
    at TypeError (native)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! pokebot-ui@1.0.0 start: `npm install; bower install --config.interactive=false; ./node_modules/.bin/brunch build --production; node ./index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pokebot-ui@1.0.0 start script 'npm install; bower install --config.interactive=false; ./node_modules/.bin/brunch build --production; node ./index.js'.
npm ERR! This is most likely a problem with the pokebot-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install; bower install --config.interactive=false; ./node_modules/.bin/brunch build --production; node ./index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pokebot-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls pokebot-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by cokeeffekt** [comment]
It seems protobuf doesn't like that version of node. Ill look into it more tonight, but i can only replicates this on node 4.2

**Comment by 4N1S** [comment]
I upgrade my node version.. But i have an another problem . I start a server and i have error..

listening on *:5000
[i] Client connected to WS
[i] Trainer Logged in!
[+] Pokestop Depleted
[i] Building Walk Path
[i] Walking to -33.8595379, 151.2048828, ; deg:70.48903705608552; dis:14
[+] Pokestop Depleted
[+] Pokestop Depleted
/Pokemonfarm/pokebot-ui/index.js:283
    socket.emit('Evnt', 'clearPolyMap');
    ^

ReferenceError: socket is not defined
    at walkTrainerPath [as _onTimeout](/Pokemonfarm/pokebot-ui/index.js:283:5)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by 4N1S** [comment]
Connection ok . but it remains blocked on the line in the console
i] Client connected to WS
[i] Trainer Logged in!
254293 1412.7388888888888 'DISNT'

**Comment by cokeeffekt** [comment]
yeh, ive been rewriting this to use another pokemon go api that supports the protobuf stuff better. Ill release soon

**Comment by 4N1S** [comment]
oki cool ! I have a bug when I no pokeball while I have HyperBall superball and ...

**Comment by cokeeffekt** [comment]
yeh the bot doesnt swap pokeball yet, its coming i guess.

**Comment by 4N1S** [comment]
manage item and transfer pokemon.. it 's very good :-)

**Comment by 4N1S** [comment]
no update ?
